[tools]
bat = "latest"
"cargo:starship" = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
hwatch = "latest"
jq = "latest"
lazygit = "latest"
ripgrep = "latest"
taplo = "latest"
tmux = "latest"
uv = "latest"
worktrunk = "latest"
zoxide = "latest"
